/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Czech
 * UTF-8 for Graphical Display
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 * Translated by Petr Zahradnik, Computer Laboratory
 * Blog and video blog Zahradnik se bavi
 * http://www.zahradniksebavi.cz
 *
 */
#ifndef LANGUAGE_CZ_UTF_H
#define LANGUAGE_CZ_UTF_H

#define MAPPER_C3C4C5_CZ
#define DISPLAY_CHARSET_ISO10646_CZ

#define WELCOME_MSG                         MACHINE_NAME _UxGT(" p艡ipraven.")
#define MSG_BACK                            _UxGT("Zp臎t")
#define MSG_SD_INSERTED                     _UxGT("Karta vlo啪ena")
#define MSG_SD_REMOVED                      _UxGT("Karta vyjmuta")
#define MSG_LCD_ENDSTOPS                    _UxGT("Endstopy") // max 8 znaku
#define MSG_MAIN                            _UxGT("Hlavn铆 nab铆dka")
#define MSG_AUTOSTART                       _UxGT("Autostart")
#define MSG_DISABLE_STEPPERS                _UxGT("Uvolnit motory")
#define MSG_DEBUG_MENU                      _UxGT("Nab铆dka lad臎n铆")
#define MSG_PROGRESS_BAR_TEST               _UxGT("Test uk. pr暖b臎hu")
#define MSG_AUTO_HOME                       _UxGT("Domovsk谩 pozice")
#define MSG_AUTO_HOME_X                     _UxGT("Dom暖 osa X")
#define MSG_AUTO_HOME_Y                     _UxGT("Dom暖 osa Y")
#define MSG_AUTO_HOME_Z                     _UxGT("Dom暖 osa Z")
#define MSG_LEVEL_BED_HOMING                _UxGT("M臎艡en铆 podlo啪ky")
#define MSG_LEVEL_BED_WAITING               _UxGT("Kliknut铆m spus钮te")
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("Dal拧铆 bod")
#define MSG_LEVEL_BED_DONE                  _UxGT("M臎艡en铆 hotovo!")
#define MSG_Z_FADE_HEIGHT                   _UxGT("V媒拧ka srovn谩v谩n铆")
#define MSG_SET_HOME_OFFSETS                _UxGT("Nastavit ofsety")
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("Ofsety nastaveny")
#define MSG_SET_ORIGIN                      _UxGT("Nastavit po膷谩tek")
#define MSG_PREHEAT_1                       _UxGT("Zah艡谩t PLA")
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" v拧e")
#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" hotend")
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" podlo啪")
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" nast")
#define MSG_PREHEAT_2                       _UxGT("Zah艡谩t ABS")
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" v拧e")
#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" hotend")
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" podlo啪")
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" nast")
#define MSG_COOLDOWN                        _UxGT("Zchladit")
#define MSG_SWITCH_PS_ON                    _UxGT("Zapnout nap谩jen铆")
#define MSG_SWITCH_PS_OFF                   _UxGT("Vypnout nap谩jen铆")
#define MSG_EXTRUDE                         _UxGT("Vytla膷it (extr.)")
#define MSG_RETRACT                         _UxGT("Zatla膷it (retr.)")
#define MSG_MOVE_AXIS                       _UxGT("Posunout osy")
#define MSG_BED_LEVELING                    _UxGT("Vyrovnat podlo啪ku")
#define MSG_LEVEL_BED                       _UxGT("Vyrovnat podlo啪ku")
#define MSG_LEVEL_CORNERS                   _UxGT("Vyrovnat rohy")
#define MSG_NEXT_CORNER                     _UxGT("Dal拧铆 roh")
#define MSG_EDITING_STOPPED                 _UxGT("Konec 煤prav s铆t臎")

#define MSG_UBL_DOING_G29                   _UxGT("Prov谩d铆m G29")
#define MSG_UBL_UNHOMED                     _UxGT("P艡eje膹te dom暖")
#define MSG_UBL_TOOLS                       _UxGT("UBL n谩stroje")
#define MSG_UBL_LEVEL_BED                   _UxGT("Unified Bed Leveling")
#define MSG_UBL_MANUAL_MESH                 _UxGT("Manu谩ln铆 s铆钮 bod暖")
#define MSG_UBL_BC_INSERT                   _UxGT("Vlo啪te kartu, zm臎艡te")
#define MSG_UBL_BC_INSERT2                  _UxGT("Zm臎艡te")
#define MSG_UBL_BC_REMOVE                   _UxGT("Odstra艌te a zm臎艡te")
#define MSG_UBL_MOVING_TO_NEXT              _UxGT("P艡esun na dal拧铆")
#define MSG_UBL_ACTIVATE_MESH               _UxGT("Aktivovat UBL")
#define MSG_UBL_DEACTIVATE_MESH             _UxGT("Deaktivovat UBL")
#define MSG_UBL_SET_BED_TEMP                _UxGT("Teplota podlo啪ky")
#define MSG_UBL_CUSTOM_BED_TEMP             MSG_UBL_SET_BED_TEMP
#define MSG_UBL_SET_HOTEND_TEMP             _UxGT("Teplota hotendu")
#define MSG_UBL_CUSTOM_HOTEND_TEMP          MSG_UBL_SET_HOTEND_TEMP
#define MSG_UBL_MESH_EDIT                   _UxGT("脷prava s铆t臎 bod暖")
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("Upravit vlastn铆 s铆钮")
#define MSG_UBL_FINE_TUNE_MESH              _UxGT("Doladit s铆钮 bod暖")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("Konec 煤prav s铆t臎")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("Vlastn铆 s铆钮")
#define MSG_UBL_BUILD_MESH_MENU             _UxGT("Vytvo艡it s铆钮")
#define MSG_UBL_BUILD_PLA_MESH              _UxGT("S铆钮 bodu PLA")
#define MSG_UBL_BUILD_ABS_MESH              _UxGT("S铆钮 bodu ABS")
#define MSG_UBL_BUILD_COLD_MESH             _UxGT("Studen谩 s铆钮 bod暖")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("Upravit v媒拧ku s铆t臎")
#define MSG_UBL_MESH_HEIGHT_AMOUNT          _UxGT("V媒拧ka")
#define MSG_UBL_VALIDATE_MESH_MENU          _UxGT("Zkontrolovat s铆钮")
#define MSG_UBL_VALIDATE_PLA_MESH           _UxGT("Kontrola s铆t臎 PLA")
#define MSG_UBL_VALIDATE_ABS_MESH           _UxGT("Kontrola s铆t臎 ABS")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("Kontrola vlast. s铆t臎")
#define MSG_UBL_CONTINUE_MESH               _UxGT("Pokra膷ovat v s铆钮i")
#define MSG_UBL_MESH_LEVELING               _UxGT("S铆钮ov茅 rovn谩n铆")
#define MSG_UBL_3POINT_MESH_LEVELING        _UxGT("3-bodove rovn谩n铆")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("Mrizkove rovn谩n铆")
#define MSG_UBL_MESH_LEVEL                  _UxGT("Srovnat podlo啪ku")
#define MSG_UBL_SIDE_POINTS                 _UxGT("Postrann铆 body")
#define MSG_UBL_MAP_TYPE                    _UxGT("Typ s铆t臎 bodu")
#define MSG_UBL_OUTPUT_MAP                  _UxGT("Exportovat s铆钮")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("Exportovat do PC")
#define MSG_UBL_OUTPUT_MAP_CSV              _UxGT("Exportovat do CSV")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("Z谩loha do PC")
#define MSG_UBL_INFO_UBL                    _UxGT("Info o UBL do PC")
#define MSG_UBL_EDIT_MESH_MENU              _UxGT("Upravit s铆钮 bod暖")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("Hustota m艡铆啪ky")
#define MSG_UBL_MANUAL_FILLIN               _UxGT("Ru膷n铆 hustota")
#define MSG_UBL_SMART_FILLIN                _UxGT("Chytr谩 hustota")
#define MSG_UBL_FILLIN_MESH                 _UxGT("Zaplnit m艡铆啪ku")
#define MSG_UBL_INVALIDATE_ALL              _UxGT("Zru拧it v拧echno")
#define MSG_UBL_INVALIDATE_CLOSEST          _UxGT("Zru拧it posledn铆")
#define MSG_UBL_FINE_TUNE_ALL               _UxGT("Upravit v拧echny")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("Upravit posledn铆")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("Ulo啪i拧t臎 s铆t铆")
#define MSG_UBL_STORAGE_SLOT                _UxGT("Pam臎钮ov媒 slot")
#define MSG_UBL_LOAD_MESH                   _UxGT("Na膷铆st s铆钮 bod暖")
#define MSG_UBL_SAVE_MESH                   _UxGT("Ulo啪it s铆钮 bod暖")
#define MSG_MESH_LOADED                     _UxGT("S铆钮 %i na膷tena")
#define MSG_MESH_SAVED                      _UxGT("S铆钮 %i ulo啪ena")
#define MSG_NO_STORAGE                      _UxGT("Nedostatek m铆sta")
#define MSG_UBL_SAVE_ERROR                  _UxGT("Err: Ulo啪it UBL")
#define MSG_UBL_RESTORE_ERROR               _UxGT("Err: Obnovit UBL")
#define MSG_UBL_Z_OFFSET_STOPPED            _UxGT("Konec Z-Offsetu")
#define MSG_UBL_STEP_BY_STEP_MENU           _UxGT("UBL Postupn臎")

#define MSG_LED_CONTROL                     _UxGT("LED Nastaven铆")
#define MSG_LEDS_ON                         _UxGT("Sv臎tla Zap")
#define MSG_LEDS_OFF                        _UxGT("Sv臎tla Vyp")
#define MSG_LED_PRESETS                     _UxGT("Sv臎tla P艡edvolby")
#define MSG_SET_LEDS_RED                    _UxGT("Sv臎tla 膶erven谩")
#define MSG_SET_LEDS_ORANGE                 _UxGT("Sv臎tla Oran啪ov谩")
#define MSG_SET_LEDS_YELLOW                 _UxGT("Sv臎tla 沤lut谩")
#define MSG_SET_LEDS_GREEN                  _UxGT("Sv臎tla Zelen谩")
#define MSG_SET_LEDS_BLUE                   _UxGT("Sv臎tla Modr谩")
#define MSG_SET_LEDS_INDIGO                 _UxGT("Sv臎tla Indigo")
#define MSG_SET_LEDS_VIOLET                 _UxGT("Sv臎tla Fialov谩")
#define MSG_SET_LEDS_WHITE                  _UxGT("Sv臎tla B铆l谩")
#define MSG_SET_LEDS_DEFAULT                _UxGT("Sv臎tla V媒choz铆")
#define MSG_CUSTOM_LEDS                     _UxGT("Vlastn铆 sv臎tla")
#define MSG_INTENSITY_R                     _UxGT("膶erven谩 intenzita")
#define MSG_INTENSITY_G                     _UxGT("Zelen谩 intezita")
#define MSG_INTENSITY_B                     _UxGT("Modr谩 intenzita")
#define MSG_INTENSITY_W                     _UxGT("B铆l谩 intenzita")
#define MSG_LED_BRIGHTNESS                  _UxGT("Jas")

#define MSG_USER_MENU                       _UxGT("Vlastn铆 p艡铆kazy")
#define MSG_MOVING                          _UxGT("Posouvani...")
#define MSG_FREE_XY                         _UxGT("Uvolnit XY")
#define MSG_MOVE_X                          _UxGT("Posunout X")
#define MSG_MOVE_Y                          _UxGT("Posunout Y")
#define MSG_MOVE_Z                          _UxGT("Posunout Z")
#define MSG_MOVE_E                          _UxGT("Extrud茅r")
#define MSG_MOVE_01MM                       _UxGT("Posunout o 0,1mm")
#define MSG_MOVE_1MM                        _UxGT("Posunout o 1mm")
#define MSG_MOVE_10MM                       _UxGT("Posunout o 10mm")
#define MSG_SPEED                           _UxGT("Rychlost")
#define MSG_BED_Z                           _UxGT("V媒拧ka podl.")
#define MSG_NOZZLE                          _UxGT("Tryska")
#define MSG_BED                             _UxGT("Podlo啪ka")
#define MSG_FAN_SPEED                       _UxGT("Rychlost vent.")
#define MSG_EXTRA_FAN_SPEED                 _UxGT("Rychlost ex. vent.")
#define MSG_FLOW                            _UxGT("Pr暖tok")
#define MSG_CONTROL                         _UxGT("Ovl谩dan铆")
#define MSG_MIN                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Min")
#define MSG_MAX                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Max")
#define MSG_FACTOR                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" Fakt")
#define MSG_AUTOTEMP                        _UxGT("Autoteplota")
#define MSG_ON                              _UxGT("Zap")
#define MSG_OFF                             _UxGT("Vyp")
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("Vybrat")
#define MSG_ACC                             _UxGT("Zrychl")
#define MSG_JERK                            _UxGT("Jerk")
#define MSG_VX_JERK                         _UxGT("Vx-jerk")
#define MSG_VY_JERK                         _UxGT("Vy-jerk")
#define MSG_VZ_JERK                         _UxGT("Vz-jerk")
#define MSG_VE_JERK                         _UxGT("Ve-jerk")
#define MSG_VELOCITY                        _UxGT("Rychlost")
#define MSG_VMAX                            _UxGT("Vmax ")
#define MSG_VMIN                            _UxGT("Vmin")
#define MSG_VTRAV_MIN                       _UxGT("VTrav min")
#define MSG_ACCELERATION                    _UxGT("Akcelerace")
#define MSG_AMAX                            _UxGT("Amax ")
#define MSG_A_RETRACT                       _UxGT("A-retrakt")
#define MSG_A_TRAVEL                        _UxGT("A-p艡ejezd")
#define MSG_STEPS_PER_MM                    _UxGT("Krok暖/mm")
#define MSG_XSTEPS                          _UxGT("Xkrok暖/mm")
#define MSG_YSTEPS                          _UxGT("Ykrok暖/mm")
#define MSG_ZSTEPS                          _UxGT("Zkrok暖/mm")
#define MSG_ESTEPS                          _UxGT("Ekrok暖/mm")
#define MSG_E1STEPS                         _UxGT("E1krok暖/mm")
#define MSG_E2STEPS                         _UxGT("E2krok暖/mm")
#define MSG_E3STEPS                         _UxGT("E3krok暖/mm")
#define MSG_E4STEPS                         _UxGT("E4krok暖/mm")
#define MSG_E5STEPS                         _UxGT("E5krok暖/mm")
#define MSG_TEMPERATURE                     _UxGT("Teplota")
#define MSG_MOTION                          _UxGT("Pohyb")
#define MSG_FILAMENT                        _UxGT("Filament")
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E na mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("Fil. Prum.")
#define MSG_ADVANCE_K                       _UxGT("K pro posun")
#define MSG_CONTRAST                        _UxGT("Kontrast LCD")
#define MSG_STORE_EEPROM                    _UxGT("Ulo啪it nastaven铆")
#define MSG_LOAD_EEPROM                     _UxGT("Na膷铆st nastaven铆")
#define MSG_RESTORE_FAILSAFE                _UxGT("Obnovit v媒choz铆")
#define MSG_INIT_EEPROM                     _UxGT("Inic. EEPROM")
#define MSG_REFRESH                         _UxGT("Obnovit")
#define MSG_WATCH                           _UxGT("Info obrazovka")
#define MSG_PREPARE                         _UxGT("P艡iprava tisku")
#define MSG_TUNE                            _UxGT("Dolad臎n铆 tisku")
#define MSG_PAUSE_PRINT                     _UxGT("Pozastavit tisk")
#define MSG_RESUME_PRINT                    _UxGT("Obnovit tisk")
#define MSG_STOP_PRINT                      _UxGT("Zastavit tisk")
#define MSG_CARD_MENU                       _UxGT("Tisknout z SD")
#define MSG_NO_CARD                         _UxGT("沤谩dn谩 SD karta")
#define MSG_DWELL                           _UxGT("Usp谩no...")
#define MSG_USERWAIT                        _UxGT("膶ek谩n铆 na u啪iv...")
#define MSG_PRINT_PAUSED                    _UxGT("Tisk pozastaven")
#define MSG_RESUMING                        _UxGT("Obnovov谩n铆 tisku")
#define MSG_PRINT_ABORTED                   _UxGT("Tisk zru拧en")
#define MSG_NO_MOVE                         _UxGT("沤谩dn媒 pohyb.")
#define MSG_KILLED                          _UxGT("P艠ERUSENO. ")
#define MSG_STOPPED                         _UxGT("ZASTAVENO. ")
#define MSG_CONTROL_RETRACT                 _UxGT("Retrakt mm")
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("V媒m臎na Re.mm")
#define MSG_CONTROL_RETRACTF                _UxGT("Retraktovat  V")
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("Zvednuti Z mm")
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("UnRet mm")
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("S UnRet mm")
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("UnRet  V")
#define MSG_CONTROL_RETRACT_RECOVER_SWAPF   _UxGT("S UnRet V")
#define MSG_AUTORETRACT                     _UxGT("AutoRetr.")
#define MSG_FILAMENTCHANGE                  _UxGT("Vym臎nit filament")
#define MSG_INIT_SDCARD                     _UxGT("Na膷铆st SD kartu")
#define MSG_CNG_SDCARD                      _UxGT("Vym臎nit SD kartu")
#define MSG_ZPROBE_OUT                      _UxGT("Sonda Z mimo podl")
#define MSG_SKEW_FACTOR                     _UxGT("Faktor zkosen铆")
#define MSG_BLTOUCH                         _UxGT("BLTouch")
#define MSG_BLTOUCH_SELFTEST                _UxGT("BLTouch Self-Test")
#define MSG_BLTOUCH_RESET                   _UxGT("BLTouch Reset")
#define MSG_BLTOUCH_DEPLOY                  _UxGT("BLTouch Vysunout")
#define MSG_BLTOUCH_STOW                    _UxGT("BLTouch Zasunout")
#define MSG_HOME                            _UxGT("Dom暖")  // Used as MSG_HOME " " MSG_X MSG_Y MSG_Z " " MSG_FIRST
#define MSG_FIRST                           _UxGT("prvn铆")
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Z ofset")
#define MSG_BABYSTEP_X                      _UxGT("Babystep X")
#define MSG_BABYSTEP_Y                      _UxGT("Babystep Y")
#define MSG_BABYSTEP_Z                      _UxGT("Babystep Z")
#define MSG_ENDSTOP_ABORT                   _UxGT("Endstop abort")
#define MSG_HEATING_FAILED_LCD              _UxGT("Chyba zah艡铆v谩n铆")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("REDUND. TEPLOTA")
#define MSG_THERMAL_RUNAWAY                 _UxGT("TEPLOTN脥 SKOK")
#define MSG_ERR_MAXTEMP                     _UxGT("VYSOK脕 TEPLOTA")
#define MSG_ERR_MINTEMP                     _UxGT("N脥ZKA TEPLOTA")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("VYS. TEPL. PODL.")
#define MSG_ERR_MINTEMP_BED                 _UxGT("N脥Z. TEPL. PODL.")
#define MSG_ERR_Z_HOMING                    _UxGT("G28 Z ZAK脕Z脕NO")
#define MSG_HALTED                          _UxGT("TISK. ZASTAVENA")
#define MSG_PLEASE_RESET                    _UxGT("Prove膹te reset")
#define MSG_SHORT_DAY                       _UxGT("d")
#define MSG_SHORT_HOUR                      _UxGT("h")
#define MSG_SHORT_MINUTE                    _UxGT("m")
#define MSG_HEATING                         _UxGT("Zah艡铆v谩n铆...")
#define MSG_HEATING_COMPLETE                _UxGT("Zah艡谩ti hotovo.")
#define MSG_BED_HEATING                     _UxGT("Zah艡铆v谩n铆 podl.")
#define MSG_BED_DONE                        _UxGT("Podlo啪ka hotova.")
#define MSG_DELTA_CALIBRATE                 _UxGT("Delta Kalibrace")
#define MSG_DELTA_CALIBRATE_X               _UxGT("Kalibrovat X")
#define MSG_DELTA_CALIBRATE_Y               _UxGT("Kalibrovat Y")
#define MSG_DELTA_CALIBRATE_Z               _UxGT("Kalibrovat Z")
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("Kalibrovat St艡ed")
#define MSG_DELTA_SETTINGS                  _UxGT("Delta nastaven铆")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("Autokalibrace")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("Nast.v媒拧ku delty")
#define MSG_DELTA_DIAG_ROD                  _UxGT("Diag rameno")
#define MSG_DELTA_HEIGHT                    _UxGT("V媒拧ka")
#define MSG_DELTA_RADIUS                    _UxGT("Polom臎r")
#define MSG_INFO_MENU                       _UxGT("O tisk谩rn臎")
#define MSG_INFO_PRINTER_MENU               _UxGT("Info o tisk谩rn臎")
#define MSG_3POINT_LEVELING                 _UxGT("3-bodov茅 rovn谩n铆")
#define MSG_LINEAR_LEVELING                 _UxGT("Line谩rni rovn谩n铆")
#define MSG_BILINEAR_LEVELING               _UxGT("Biline谩rn铆 rovn谩n铆")
#define MSG_UBL_LEVELING                    _UxGT("Unified Bed Leveling")
#define MSG_MESH_LEVELING                   _UxGT("M艡铆啪kov茅 rovn谩n铆")
#define MSG_INFO_STATS_MENU                 _UxGT("Statistika")
#define MSG_INFO_BOARD_MENU                 _UxGT("Info o desce")
#define MSG_INFO_THERMISTOR_MENU            _UxGT("Termistory")
#define MSG_INFO_EXTRUDERS                  _UxGT("Extrud茅ry")
#define MSG_INFO_BAUDRATE                   _UxGT("Rychlost")
#define MSG_INFO_PROTOCOL                   _UxGT("Protokol")
#define MSG_CASE_LIGHT                      _UxGT("Osv臎tlen铆")
#define MSG_CASE_LIGHT_BRIGHTNESS           _UxGT("Jas sv臎tla")

#if LCD_WIDTH >= 20
  #define MSG_INFO_PRINT_COUNT              _UxGT("Po膷et tisk暖")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Dokon膷eno")
  #define MSG_INFO_PRINT_TIME               _UxGT("Celkov媒 膷as")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Nejdel拧铆 tisk")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Celkem vytla膷eno")
#else
  #define MSG_INFO_PRINT_COUNT              _UxGT("Tisky")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Hotovo")
  #define MSG_INFO_PRINT_TIME               _UxGT("膶as")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Nejdel拧铆")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Vytla膷eno")
#endif

#define MSG_INFO_MIN_TEMP                   _UxGT("Teplota min")
#define MSG_INFO_MAX_TEMP                   _UxGT("Teplota max")
#define MSG_INFO_PSU                        _UxGT("Nap. zdroj")
#define MSG_DRIVE_STRENGTH                  _UxGT("Buzen铆 motor暖")
#define MSG_DAC_PERCENT                     _UxGT("Motor %")
#define MSG_DAC_EEPROM_WRITE                _UxGT("Ulo啪it do EEPROM")
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("PRINT PAUSED")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("RESUME OPTIONS:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("Je拧t臎 vytla膷it")
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("Obnovit tisk")
#define MSG_FILAMENT_CHANGE_MINTEMP         _UxGT("Min. teplota je ")
#define MSG_FILAMENT_CHANGE_NOZZLE          _UxGT("  Tryska: ")
#define MSG_ERR_HOMING_FAILED               _UxGT("Parkov谩n铆 selhalo")
#define MSG_ERR_PROBING_FAILED              _UxGT("Kalibrace selhala")

#if LCD_HEIGHT >= 4
  // Up to 3 lines allowed
  #define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("膶ekejte pros铆m")
  #define MSG_FILAMENT_CHANGE_INIT_2          _UxGT("na zah谩jen铆")
  #define MSG_FILAMENT_CHANGE_INIT_3          _UxGT("v媒m臎ny filamentu")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("膶ekejte pros铆m")
  #define MSG_FILAMENT_CHANGE_UNLOAD_2        _UxGT("na vysunuti")
  #define MSG_FILAMENT_CHANGE_UNLOAD_3        _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("Vlo啪te filament")
  #define MSG_FILAMENT_CHANGE_INSERT_2        _UxGT("a stiskn臎te")
  #define MSG_FILAMENT_CHANGE_INSERT_3        _UxGT("tla膷铆tko...")
  #define MSG_FILAMENT_CHANGE_HEAT_1          _UxGT("Klikn臎te pro")
  #define MSG_FILAMENT_CHANGE_HEAT_2          _UxGT("nah艡谩t铆 trysky")
  #define MSG_FILAMENT_CHANGE_HEATING_1       _UxGT("膶ekejte pros铆m")
  #define MSG_FILAMENT_CHANGE_HEATING_2       _UxGT("na nah艡谩t铆 tr.")
  #define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("膶ekejte pros铆m")
  #define MSG_FILAMENT_CHANGE_LOAD_2          _UxGT("na zaveden铆")
  #define MSG_FILAMENT_CHANGE_LOAD_3          _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("膶ekejte pros铆m")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("na vytla膷en铆")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_3       _UxGT("filamentu")
  #define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("膶ekejte pros铆m")
  #define MSG_FILAMENT_CHANGE_RESUME_2        _UxGT("na pokra膷ov谩n铆")
  #define MSG_FILAMENT_CHANGE_RESUME_3        _UxGT("tisku")
#else // LCD_HEIGHT < 4
  // Up to 2 lines allowed
  #define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("膶ekejte...")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("Vysouv谩n铆...")
  #define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("Vlo啪te, klikn臎te")
  #define MSG_FILAMENT_CHANGE_HEATING_1       _UxGT("Nah艡铆v谩n铆...")
  #define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("Zav谩d臎n铆...")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("Vytla膷ov谩n铆...")
  #define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("Pokra膷ov谩n铆...")
#endif // LCD_HEIGHT < 4

#endif // LANGUAGE_CZ_UTF_H
