/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Russian
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 */
#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define MAPPER_D0D1                // For Cyrillic
#define DISPLAY_CHARSET_ISO10646_5

#define WELCOME_MSG                         MACHINE_NAME _UxGT(" 袚芯褌芯胁.")
#define MSG_BACK                            _UxGT("袧邪蟹邪写")
#define MSG_SD_INSERTED                     _UxGT("袣邪褉褌邪 胁褋褌邪胁谢械薪邪")
#define MSG_SD_REMOVED                      _UxGT("袣邪褉褌邪 懈蟹胁谢械褔械薪邪")
#define MSG_LCD_ENDSTOPS                    _UxGT("袣芯薪褑械胁懈泻懈")
#define MSG_MAIN                            _UxGT("袦械薪褞")
#define MSG_AUTOSTART                       _UxGT("袗胁褌芯褋褌邪褉褌")
#define MSG_DISABLE_STEPPERS                _UxGT("袙褘泻谢. 写胁懈谐邪褌械谢懈")
#define MSG_DEBUG_MENU                      _UxGT("袦械薪褞 芯褌谢邪写泻懈")
#define MSG_PROGRESS_BAR_TEST               _UxGT("孝械褋褌 懈薪写懈泻邪褌芯褉邪")
#define MSG_AUTO_HOME                       _UxGT("袗胁褌芯 袩邪褉泻芯胁泻邪")
#define MSG_AUTO_HOME_X                     _UxGT("袩邪褉泻芯胁泻邪 X")
#define MSG_AUTO_HOME_Y                     _UxGT("袩邪褉泻芯胁泻邪 Y")
#define MSG_AUTO_HOME_Z                     _UxGT("袩邪褉泻芯胁泻邪 Z")
#define MSG_LEVEL_BED_HOMING                _UxGT("袧褍谢械胁芯械 锌芯谢芯卸")
#define MSG_LEVEL_BED_WAITING               _UxGT("袧邪卸屑懈褌械 薪邪褔邪褌褜")
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("小谢械写褍褞褖邪褟 褌芯褔泻邪")
#define MSG_LEVEL_BED_DONE                  _UxGT("袙褘褉邪胁薪懈薪胁邪懈械 谐芯褌芯胁芯!")
#define MSG_Z_FADE_HEIGHT                   _UxGT("袙褘褋芯褌邪 褋锌邪写邪")
#define MSG_SET_HOME_OFFSETS                _UxGT("袟邪锌芯屑薪懈褌褜 锌邪褉泻芯胁泻褍")
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("袣芯褉褉械泻褑懈懈 锌褉懈屑械薪")
#define MSG_SET_ORIGIN                      _UxGT("袟邪锌芯屑薪懈褌褜 薪芯谢褜")
#define MSG_PREHEAT_1                       _UxGT("袩褉械写薪邪谐褉械胁 PLA")
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" 袙褋褢")
#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" 小芯锌谢芯")
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" 小褌芯谢")
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" 袧邪褋褌褉.")
#define MSG_PREHEAT_2                       _UxGT("袩褉械写薪邪谐褉械胁 ABS")
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" 袙褋褢")
#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" 小芯锌谢芯")
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" 小褌芯谢")
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" 袧邪褋褌褉.")
#define MSG_COOLDOWN                        _UxGT("袨褏谢邪卸写械薪懈械")
#define MSG_SWITCH_PS_ON                    _UxGT("袙泻谢褞褔懈褌褜 袩懈褌邪薪懈械")
#define MSG_SWITCH_PS_OFF                   _UxGT("袨褌泻谢褞褔懈褌褜 袩懈褌邪薪懈械")
#define MSG_EXTRUDE                         _UxGT("协泻褋褌褉褍蟹懈褟")
#define MSG_RETRACT                         _UxGT("袙褌褟谐懈胁邪薪懈械")
#define MSG_MOVE_AXIS                       _UxGT("袛胁懈卸械薪懈械 锌芯 芯褋褟屑")
#define MSG_BED_LEVELING                    _UxGT("袣邪谢懈斜褉芯胁邪褌褜 褋褌芯谢")
#define MSG_LEVEL_BED                       _UxGT("袣邪谢懈斜褉芯胁邪褌褜 褋褌芯谢")
#define MSG_EDITING_STOPPED                 _UxGT("袪械写. 褋械褌泻懈 蟹邪胁械褉褕械薪邪")
#define MSG_USER_MENU                       _UxGT("小胁芯懈 泻芯屑屑邪薪写褘")
#define MSG_UBL_DOING_G29                   _UxGT("袙褘锌芯谢薪褟械屑 G29")
#define MSG_UBL_UNHOMED                     _UxGT("袩邪褉泻褍械屑 褋薪邪褔邪谢邪 XYZ")
#define MSG_UBL_TOOLS                       _UxGT("校褌懈谢懈褌褘 UBL")
#define MSG_UBL_LEVEL_BED                   _UxGT("袣邪谢懈斜褉芯胁泻邪 UBL")
#define MSG_UBL_MANUAL_MESH                 _UxGT("袩芯褋褌褉. 褋械褌泻褍 芯褌 褉褍泻懈")
#define MSG_UBL_BC_INSERT                   _UxGT("袩芯褋褌. 褕懈屑屑 懈 懈蟹屑械褉.")
#define MSG_UBL_BC_INSERT2                  _UxGT("袠蟹屑械褉械薪懈械")
#define MSG_UBL_BC_REMOVE                   _UxGT("校写邪谢. 懈 懈蟹屑械褉. 褋褌芯谢")
#define MSG_UBL_MOVING_TO_NEXT              _UxGT("袛胁懈谐邪械屑褋褟 写邪谢褜褕械")
#define MSG_UBL_ACTIVATE_MESH               _UxGT("袗泻褌懈胁懈褉芯胁邪褌褜 UBL")
#define MSG_UBL_DEACTIVATE_MESH             _UxGT("袙褘泻谢褞褔懈褌褜 UBL")
#define MSG_UBL_SET_BED_TEMP                _UxGT("孝械屑锌械褉邪褌褍褉邪 褋褌芯谢邪")
#define MSG_UBL_CUSTOM_BED_TEMP             MSG_UBL_SET_BED_TEMP
#define MSG_UBL_SET_HOTEND_TEMP             _UxGT("孝械屑锌械褉邪褌褍褉邪 褋芯锌谢邪")
#define MSG_UBL_CUSTOM_HOTEND_TEMP          MSG_UBL_SET_HOTEND_TEMP
#define MSG_UBL_MESH_EDIT                   _UxGT("袪械写邪泻褌芯褉 褋械褌芯泻")
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("袪械写邪泻褌. 褋胁芯褞 褋械褌泻褍")
#define MSG_UBL_FINE_TUNE_MESH              _UxGT("孝芯褔. 薪邪褋褌褉芯泄泻邪 褋械褌泻懈")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("袪械写. 褋械褌泻懈 蟹邪胁械褉褕械薪芯")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("袩芯褋褌褉芯懈褌褜 褋胁芯褞 褋械褌泻褍")
#define MSG_UBL_BUILD_MESH_MENU             _UxGT("袩芯褋褌褉芯懈褌褜 褋械褌泻褍")
#define MSG_UBL_BUILD_PLA_MESH              _UxGT("袩芯褋褌褉芯懈褌褜 褋械褌泻褍 PLA")
#define MSG_UBL_BUILD_ABS_MESH              _UxGT("袩芯褋褌褉芯懈褌褜 褋械褌泻褍 ABS")
#define MSG_UBL_BUILD_COLD_MESH             _UxGT("袩芯褋褌褉芯懈褌褜 褏芯谢. 褋械褌泻褍")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("校褋褌邪薪. 胁褘褋芯褌褍 褋械褌泻懈")
#define MSG_UBL_MESH_HEIGHT_AMOUNT          _UxGT("袙褘褋芯褌邪")
#define MSG_UBL_VALIDATE_MESH_MENU          _UxGT("袩褉芯胁械褉懈褌褜 褋械褌泻褍")
#define MSG_UBL_VALIDATE_PLA_MESH           _UxGT("袩褉芯胁械褉懈褌褜 褋械褌泻褍 PLA")
#define MSG_UBL_VALIDATE_ABS_MESH           _UxGT("袩褉芯胁械褉懈褌褜 褋械褌泻褍 ABS")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("袩褉芯胁械褉懈褌褜 褋胁芯褞 褋械褌泻褍")
#define MSG_UBL_CONTINUE_MESH               _UxGT("袩褉芯写芯谢卸懈褌褜 褋械褌泻褍")
#define MSG_UBL_MESH_LEVELING               _UxGT("袣邪谢懈斜褉芯胁泻邪 褋械褌泻懈")
#define MSG_UBL_3POINT_MESH_LEVELING        _UxGT("袣邪谢懈斜褉芯胁泻邪 3-褏 褌芯褔械泻")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("袣邪谢懈斜褉芯胁泻邪 褉邪褋褌械褉邪")
#define MSG_UBL_MESH_LEVEL                  _UxGT("袙褘褉芯胁薪懈褌褜 褋械褌泻褍")
#define MSG_UBL_SIDE_POINTS                 _UxGT("袣褉邪泄薪懈械 褌芯褔泻懈")
#define MSG_UBL_MAP_TYPE                    _UxGT("孝懈锌 泻邪褉褌褘")
#define MSG_UBL_OUTPUT_MAP                  _UxGT("袙褘胁械褋褌懈 泻邪褉褌褍 褋械褌泻懈")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("袙褘胁械褋褌懈 薪邪 褏芯褋褌")
#define MSG_UBL_OUTPUT_MAP_CSV              _UxGT("袙褘胁械褋褌懈 胁 CSV")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("袟邪斜械泻邪锌懈褌褜 褋械褌泻褍")
#define MSG_UBL_INFO_UBL                    _UxGT("袙褘写邪褔邪 懈薪褎芯褉. UBL")
#define MSG_UBL_EDIT_MESH_MENU              _UxGT("袪械写邪泻褌懈褉芯胁邪褌褜 褋械褌泻褍")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("袟邪锌芯谢薪懈褌褜 蟹薪邪褔械薪懈褟")
#define MSG_UBL_MANUAL_FILLIN               _UxGT("袪褍褔薪芯械 蟹邪锌芯谢薪械薪懈械")
#define MSG_UBL_SMART_FILLIN                _UxGT("校屑械薪芯械 蟹邪锌芯谢薪械薪懈械")
#define MSG_UBL_FILLIN_MESH                 _UxGT("袟邪锌芯谢薪懈褌褜 褋械褌泻褍")
#define MSG_UBL_INVALIDATE_ALL              _UxGT("袗薪薪褍谢懈褉芯胁邪褌褜 胁褋褢")
#define MSG_UBL_INVALIDATE_CLOSEST          _UxGT("袗薪薪褍谢懈褉. 斜谢懈卸. 褌芯褔泻褍")
#define MSG_UBL_FINE_TUNE_ALL               _UxGT("孝芯褔. 薪邪褋褌褉芯泄泻邪 胁褋械谐芯")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("袧邪褋褌褉. 斜谢懈卸. 褌芯褔泻懈")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("啸褉邪薪懈谢懈褖械 褋械褌械泄")
#define MSG_UBL_STORAGE_SLOT                _UxGT("小谢芯褌 锌邪屑褟褌懈")
#define MSG_UBL_LOAD_MESH                   _UxGT("袟邪谐褉褍蟹懈褌褜 褋褌芯谢 褋械褌泻懈")
#define MSG_UBL_SAVE_MESH                   _UxGT("小芯褏褉邪薪懈褌褜 褋褌芯谢 褋械褌泻懈")
#define MSG_UBL_SAVE_ERROR                  _UxGT("袨褕懈斜泻邪: 小芯褏褉. UBL")
#define MSG_UBL_RESTORE_ERROR               _UxGT("袨褕懈斜泻邪: 袟邪谐褉褍蟹泻懈 UBL")
#define MSG_UBL_Z_OFFSET_STOPPED            _UxGT("小屑械褖械薪懈械 Z 芯褋褌邪薪芯胁.")
#define MSG_UBL_STEP_BY_STEP_MENU           _UxGT("袩芯褕邪谐芯胁褘泄 UBL")
#define MSG_MOVING                          _UxGT("袛胁懈卸械屑褋褟...")
#define MSG_FREE_XY                         _UxGT("袨褋胁芯斜芯卸写邪械屑 XY")
#define MSG_MOVE_X                          _UxGT("袛胁懈卸械薪懈械 锌芯 X")
#define MSG_MOVE_Y                          _UxGT("袛胁懈卸械薪懈械 锌芯 Y")
#define MSG_MOVE_Z                          _UxGT("袛胁懈卸械薪懈械 锌芯 Z")
#define MSG_MOVE_E                          _UxGT("协泻褋褌褉褍写械褉")
#define MSG_MOVE_01MM                       _UxGT("袛胁懈卸械薪懈械 0.1mm")
#define MSG_MOVE_1MM                        _UxGT("袛胁懈卸械薪懈械 1mm")
#define MSG_MOVE_10MM                       _UxGT("袛胁懈卸械薪懈械 10mm")
#define MSG_SPEED                           _UxGT("小泻芯褉芯褋褌褜")
#define MSG_BED_Z                           _UxGT("Z 褋褌芯谢邪")
#define MSG_NOZZLE                          LCD_STR_THERMOMETER _UxGT(" 小芯锌谢芯")
#define MSG_BED                             LCD_STR_THERMOMETER _UxGT(" 小褌芯谢")
#define MSG_FAN_SPEED                       _UxGT("袣褍谢械褉")
#define MSG_FLOW                            _UxGT("袩芯褌芯泻")
#define MSG_CONTROL                         _UxGT("袧邪褋褌褉芯泄泻懈")
#define MSG_MIN                             LCD_STR_THERMOMETER _UxGT(" 袦懈薪懈屑褍屑")
#define MSG_MAX                             LCD_STR_THERMOMETER _UxGT(" 袦邪泻褋懈屑褍屑")
#define MSG_FACTOR                          LCD_STR_THERMOMETER _UxGT(" 肖邪泻褌芯褉")
#define MSG_AUTOTEMP                        _UxGT("袗胁褌芯褌械屑锌械褉邪褌褍褉邪")
#define MSG_ON                              _UxGT("袙泻谢. ")
#define MSG_OFF                             _UxGT("袨褌泻谢. ")
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("袙褘斜芯褉")
#define MSG_ACC                             _UxGT("校褋泻芯褉械薪懈械")
#define MSG_JERK                            _UxGT("袪褘胁芯泻")
#define MSG_VX_JERK                         _UxGT("Vx-褉褘胁芯泻")
#define MSG_VY_JERK                         _UxGT("Vy-褉褘胁芯泻")
#define MSG_VZ_JERK                         _UxGT("Vz-褉褘胁芯泻")
#define MSG_VE_JERK                         _UxGT("Ve-褉褘胁芯泻")
#define MSG_VELOCITY                        _UxGT("小泻芯褉芯褋褌褜")
#define MSG_VMAX                            _UxGT("V屑邪泻褋 ")
#define MSG_VMIN                            _UxGT("V屑懈薪")
#define MSG_VTRAV_MIN                       _UxGT("V锌褍褌械褕. 屑懈薪")
#define MSG_ACCELERATION                    _UxGT("校褋泻芯褉械薪懈械")
#define MSG_AMAX                            _UxGT("A屑邪泻褋")
#define MSG_A_RETRACT                       _UxGT("A-胁褌褟谐懈胁邪薪懈械")
#define MSG_A_TRAVEL                        _UxGT("A-锌褍褌械褕.")
#define MSG_STEPS_PER_MM                    _UxGT("楔邪谐/屑屑")
#define MSG_XSTEPS                          _UxGT("X 褕邪谐/屑屑")
#define MSG_YSTEPS                          _UxGT("Y 褕邪谐/屑屑")
#define MSG_ZSTEPS                          _UxGT("Z 褕邪谐/屑屑")
#define MSG_ESTEPS                          _UxGT("E 褕邪谐/屑屑")
#define MSG_E1STEPS                         _UxGT("E1 褕邪谐/屑屑")
#define MSG_E2STEPS                         _UxGT("E2 褕邪谐/屑屑")
#define MSG_E3STEPS                         _UxGT("E3 褕邪谐/屑屑")
#define MSG_E4STEPS                         _UxGT("E4 褕邪谐/屑屑")
#define MSG_E5STEPS                         _UxGT("E5 褕邪谐/屑屑")
#define MSG_TEMPERATURE                     _UxGT("孝械屑锌械褉邪褌褍褉邪")
#define MSG_MOTION                          _UxGT("袦械褏邪薪懈泻邪")
#define MSG_FILAMENT                        _UxGT("袩褉褍褌芯泻")
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E 胁 mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("袛懈邪屑械褌褉 锌褉褍褌泻邪")
#define MSG_ADVANCE_K                       _UxGT("K 锌褉芯写胁懈卸械薪懈褟")
#define MSG_CONTRAST                        _UxGT("袣芯薪褌褉邪褋褌 LCD")
#define MSG_STORE_EEPROM                    _UxGT("小芯褏褉邪薪懈褌褜 胁 EEPROM")
#define MSG_LOAD_EEPROM                     _UxGT("小褔懈褌邪褌褜 懈蟹 EEPROM")
#define MSG_RESTORE_FAILSAFE                _UxGT("小斜褉芯褋 EEPROM")
#define MSG_INIT_EEPROM                     _UxGT("袠薪懈褑. EEPROM")
#define MSG_REFRESH                         _UxGT("袨斜薪芯胁懈褌褜")
#define MSG_WATCH                           _UxGT("袨斜蟹芯褉")
#define MSG_PREPARE                         _UxGT("袛械泄褋褌胁懈褟")
#define MSG_TUNE                            _UxGT("袧邪褋褌褉芯泄泻懈")
#define MSG_PAUSE_PRINT                     _UxGT("袩邪褍蟹邪 锌械褔邪褌懈")
#define MSG_RESUME_PRINT                    _UxGT("袩褉芯写芯谢卸懈褌褜 锌械褔邪褌褜")
#define MSG_STOP_PRINT                      _UxGT("袨褋褌邪薪芯胁懈褌褜 锌械褔邪褌褜")
#define MSG_CARD_MENU                       _UxGT("袨斜蟹芯褉 泻邪褉褌褘")
#define MSG_NO_CARD                         _UxGT("袧械褌 泻邪褉褌褘")
#define MSG_DWELL                           _UxGT("小芯薪...")
#define MSG_USERWAIT                        _UxGT("袩褉芯写芯谢卸懈褌褜...")
#define MSG_PRINT_PAUSED                    _UxGT("袩械褔邪褌褜 芯褋褌邪薪芯胁谢械薪邪")
#define MSG_RESUMING                        _UxGT("袙芯蟹芯斜薪芯胁谢械薪懈械...")
#define MSG_PRINT_ABORTED                   _UxGT("袨褌屑械薪邪 锌械褔邪褌懈")
#define MSG_NO_MOVE                         _UxGT("袧械褌 写胁懈卸械薪懈褟.")
#define MSG_KILLED                          _UxGT("校袘袠孝袨.")
#define MSG_STOPPED                         _UxGT("袨小孝袗袧袨袙袥袝袧袨.")
#define MSG_CONTROL_RETRACT                 _UxGT("袙褌褟谐懈胁邪薪懈械 mm")
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("袙褌褟谐. 褋屑械薪褘 mm")
#define MSG_CONTROL_RETRACTF                _UxGT("袙褌褟谐懈胁邪薪懈械 V")
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("袙褌褟谐. 锌褉褘卸泻邪 mm")
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("袙芯蟹胁褉邪褌 mm")
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("袙芯蟹胁褉邪褌 褋屑械薪褘 mm")
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("袙芯蟹胁褉邪褌  V")
#define MSG_AUTORETRACT                     _UxGT("袗胁褌芯 袙褌褟谐懈胁邪薪懈械")
#define MSG_FILAMENTCHANGE                  _UxGT("小屑械薪邪 锌褉褍褌泻邪")
#define MSG_INIT_SDCARD                     _UxGT("袠薪懈褑. 泻邪褉褌褍")
#define MSG_CNG_SDCARD                      _UxGT("小屑械薪懈褌褜 泻邪褉褌褍")
#define MSG_ZPROBE_OUT                      _UxGT("Z 写邪褌褔懈泻 胁薪械 褋褌芯谢邪")
#define MSG_BLTOUCH                         _UxGT("BLTouch")
#define MSG_BLTOUCH_SELFTEST                _UxGT("孝械褋褌懈褉芯胁邪薪懈械 BLTouch")
#define MSG_BLTOUCH_RESET                   _UxGT("小斜褉芯褋 BLTouch")
#define MSG_BLTOUCH_DEPLOY                  _UxGT("校褋褌邪薪芯胁泻邪 BLTouch")
#define MSG_BLTOUCH_STOW                    _UxGT("袧邪斜懈胁泻邪 BLTouch")
#define MSG_HOME                            _UxGT("袩邪褉泻褍泄")
#define MSG_FIRST                           _UxGT("锌械褉胁褘泄")
#define MSG_ZPROBE_ZOFFSET                  _UxGT("小屑械褖械薪懈械 Z")
#define MSG_BABYSTEP_X                      _UxGT("袦懈泻褉芯褕邪谐 X")
#define MSG_BABYSTEP_Y                      _UxGT("袦懈泻褉芯褕邪谐 Y")
#define MSG_BABYSTEP_Z                      _UxGT("袦懈泻褉芯褕邪谐 Z")
#define MSG_ENDSTOP_ABORT                   _UxGT("小褉邪斜芯褌邪谢 泻芯薪褑械胁懈泻")
#define MSG_HEATING_FAILED_LCD              _UxGT("袪邪蟹芯谐褉械胁 薪械 褍写邪谢褋褟")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("袨褕懈斜泻邪: T 褉械写.")
#define MSG_THERMAL_RUNAWAY                 _UxGT("孝袝袩袥袨 校袘袝袚袗袧袠携!")
#define MSG_ERR_MAXTEMP                     _UxGT("袨褕懈斜泻邪: 孝 屑邪泻褋.")
#define MSG_ERR_MINTEMP                     _UxGT("袨褕懈斜泻邪: 孝 屑懈薪.")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("袨褕懈斜泻邪:孝 屑邪泻褋.褋褌芯谢")
#define MSG_ERR_MINTEMP_BED                 _UxGT("袨褕懈斜泻邪:孝 屑懈薪.褋褌芯谢")
#define MSG_ERR_Z_HOMING                    _UxGT("G28 Z 袟邪锌褉械褖械薪芯")
#define MSG_HALTED                          _UxGT("袩袪袠袧孝袝袪 袨小孝袗袧袨袙袥袝袧")
#define MSG_PLEASE_RESET                    _UxGT("袧邪卸屑懈褌械 褉械褋械褌")
#define MSG_SHORT_DAY                       _UxGT("写") // One character only
#define MSG_SHORT_HOUR                      _UxGT("褔") // One character only
#define MSG_SHORT_MINUTE                    _UxGT("屑") // One character only
#define MSG_HEATING                         _UxGT("袧邪谐褉械胁邪褞 褋芯锌谢芯...")
#define MSG_HEATING_COMPLETE                _UxGT("袧邪谐褉械胁 胁褘锌芯谢薪械薪")
#define MSG_BED_HEATING                     _UxGT("袧邪谐褉械胁邪褞 褋褌芯谢")
#define MSG_BED_DONE                        _UxGT("小褌芯谢 褉邪蟹芯谐褉械褌")
#define MSG_DELTA_CALIBRATE                 _UxGT("袣邪谢懈斜褉芯胁泻邪 Delta")
#define MSG_DELTA_CALIBRATE_X               _UxGT("袣邪谢懈斜褉芯胁邪褌褜 X")
#define MSG_DELTA_CALIBRATE_Y               _UxGT("袣邪谢懈斜褉芯胁邪褌褜 Y")
#define MSG_DELTA_CALIBRATE_Z               _UxGT("袣邪谢懈斜褉芯胁邪褌褜 Z")
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("袣邪谢懈斜褉芯胁邪褌褜 褑械薪褌褉")
#define MSG_DELTA_SETTINGS                  _UxGT("袩芯泻. 薪邪褋褌褉芯泄泻懈 Delta")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("袗胁褌芯 泻邪谢懈斜褉芯胁泻邪")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("袟邪写邪褌褜 胁褘褋芯褌褍 Delta")
#define MSG_INFO_MENU                       _UxGT("袨 锌褉懈薪褌械褉械")
#define MSG_INFO_PRINTER_MENU               _UxGT("袠薪褎. 芯 锌褉懈薪褌械褉械")
#define MSG_3POINT_LEVELING                 _UxGT("袣邪谢懈斜褉芯胁泻邪 3-褏 褌芯褔械泻")
#define MSG_LINEAR_LEVELING                 _UxGT("袥懈薪械泄薪邪褟 泻邪谢懈斜褉芯胁泻邪")
#define MSG_BILINEAR_LEVELING               _UxGT("袘懈谢懈薪械泄薪邪褟 泻邪谢懈斜褉.")
#define MSG_UBL_LEVELING                    _UxGT("袣邪谢懈斜褉芯胁泻邪 UBL")
#define MSG_MESH_LEVELING                   _UxGT("袣邪谢懈斜褉芯胁泻邪 褋械褌泻懈")
#define MSG_INFO_STATS_MENU                 _UxGT("小褌邪褌懈褋褌懈泻邪 锌褉懈薪褌械褉邪")
#define MSG_INFO_BOARD_MENU                 _UxGT("袠薪褎芯褉屑邪褑懈褟 芯 锌谢邪褌械")
#define MSG_INFO_THERMISTOR_MENU            _UxGT("孝械褉屑懈褋褌芯褉褘")
#define MSG_INFO_EXTRUDERS                  _UxGT("协泻褋褌褉褍写械褉褘")
#define MSG_INFO_BAUDRATE                   _UxGT("袘芯写")
#define MSG_INFO_PROTOCOL                   _UxGT("袩褉芯褌芯泻芯谢")
#define MSG_CASE_LIGHT                      _UxGT("袣芯褉锌褍褋薪芯械 芯褋胁械褖械薪懈械")
#define MSG_CASE_LIGHT_BRIGHTNESS           _UxGT("携褉泻芯褋褌褜 芯褋胁械褖械薪懈褟")
#if LCD_WIDTH >= 20
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("袟邪泻芯薪褔械薪芯")
  #define MSG_INFO_PRINT_TIME               _UxGT("袩芯谢薪芯械 胁褉械屑褟 锌械褔邪褌懈")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("袛谢懈薪薪邪 褎懈谢邪屑械薪褌邪")
#else
  #define MSG_INFO_PRINT_COUNT              _UxGT("袨褌锌械褔邪褌泻芯胁")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("袟邪泻芯薪褔械薪芯")
  #define MSG_INFO_PRINT_TIME               _UxGT("袙褋械谐芯")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("袧邪懈斜芯谢褜褕械械")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("袙褘写邪胁谢械薪芯")
#endif
#define MSG_INFO_MIN_TEMP                   _UxGT("袦懈薪. 孝")
#define MSG_INFO_MAX_TEMP                   _UxGT("袦邪泻褋. 孝")
#define MSG_INFO_PSU                        _UxGT("袘谢芯泻 锌懈褌邪薪懈褟")
#define MSG_DRIVE_STRENGTH                  _UxGT("小懈谢邪 锌褉懈胁芯写邪")
#define MSG_DAC_PERCENT                     _UxGT("袩褉懈胁芯写 %")
#define MSG_DAC_EEPROM_WRITE                _UxGT("袟邪锌懈褋懈 DAC EEPROM")
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("袩袝效袗孝鞋 袨小孝袗袧袨袙袥袝袧袗")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("袨袩笑袠袠 袙袨袟袨袘袧袨袙袥袝袧袠携:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("袙褘写邪胁懈褌褜 械褖褢")
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("袙芯蟹芯斜薪芯胁懈褌褜 锌械褔邪褌褜")
#define MSG_FILAMENT_CHANGE_MINTEMP         _UxGT("袦懈薪. 褌械屑锌械褉邪褌褍褉邪")
#define MSG_FILAMENT_CHANGE_NOZZLE          _UxGT("  小芯锌谢邪: ")
//
// Filament Change screens show up to 3 lines on a 4-line display
//                        ...or up to 2 lines on a 3-line display
//
#if LCD_HEIGHT >= 4
  #define MSG_FILAMENT_CHANGE_INIT_1      _UxGT("袨卸懈写邪泄褌械")
  #define MSG_FILAMENT_CHANGE_INIT_2      _UxGT("薪邪褔邪谢邪 褋屑械薪褘")
  #define MSG_FILAMENT_CHANGE_INIT_3      _UxGT("褎懈谢邪屑械薪褌邪")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1    _UxGT("袨卸懈写邪泄褌械")
  #define MSG_FILAMENT_CHANGE_UNLOAD_2    _UxGT("胁褘谐褉褍蟹泻懈 褎懈谢邪屑械薪褌邪")
  #define MSG_FILAMENT_CHANGE_INSERT_1    _UxGT("袙褋褌邪胁褜褌械 褎懈谢邪屑械薪褌")
  #define MSG_FILAMENT_CHANGE_INSERT_2    _UxGT("懈 薪邪卸屑懈褌械 泻薪芯锌泻褍")
  #define MSG_FILAMENT_CHANGE_INSERT_3    _UxGT("写谢褟 锌褉芯写芯谢卸械薪懈褟...")
  #define MSG_FILAMENT_CHANGE_HEAT_1      _UxGT("袧邪卸屑懈褌械 泻薪芯锌泻褍 写谢褟")
  #define MSG_FILAMENT_CHANGE_HEAT_2      _UxGT("薪邪谐褉械胁邪 褋芯锌谢邪...")
  #define MSG_FILAMENT_CHANGE_HEATING_1   _UxGT("袧邪谐褉械胁 褋芯锌谢邪")
  #define MSG_FILAMENT_CHANGE_HEATING_2   _UxGT("袞写懈褌械...")
  #define MSG_FILAMENT_CHANGE_LOAD_1      _UxGT("袨卸懈写邪泄褌械")
  #define MSG_FILAMENT_CHANGE_LOAD_2      _UxGT("蟹邪谐褉褍蟹泻懈 褎懈谢邪屑械薪褌邪")
  #define MSG_FILAMENT_CHANGE_RESUME_1    _UxGT("袨卸懈写邪泄褌械")
  #define MSG_FILAMENT_CHANGE_RESUME_2    _UxGT("胁芯蟹芯斜薪芯胁谢械薪懈褟")
#else // LCD_HEIGHT < 4
  #define MSG_FILAMENT_CHANGE_INIT_1      _UxGT("袨卸懈写邪泄褌械...")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1    _UxGT("袙褘谐褉褍蟹泻邪...")
  #define MSG_FILAMENT_CHANGE_INSERT_1    _UxGT("袙褋褌邪胁褜 懈 薪邪卸屑懈")
  #define MSG_FILAMENT_CHANGE_HEATING_1   _UxGT("袧邪谐褉械胁...")
  #define MSG_FILAMENT_CHANGE_LOAD_1      _UxGT("袟邪谐褉褍蟹泻邪...")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1   _UxGT("袙褘写邪胁谢懈胁邪薪懈械...")
  #define MSG_FILAMENT_CHANGE_RESUME_1    _UxGT("袙芯蟹芯斜薪芯胁谢械薪懈械...")
#endif // LCD_HEIGHT < 4

#endif // LANGUAGE_RU_H
